name: build images

on:
  push:
    branches:
      - 'trunk'

  pull_request_target:
    types: [opened, reopened]
    branches:
      - 'trunk'

  schedule:
    - cron:  '0 0 * * WED'

env:
  REGISTRY: ghcr.io

jobs:
  terraform-build:
    strategy:
      matrix:
        version: ["1.1", "1.2", "1.3"]
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Github Docker Registry
        uses: docker/login-action@v2
        if: github.event_name != 'pull_request'
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/ozee-io/terraform:${{ matrix.version }}
          build-args: |
              install_script="terraform.sh"
              minor_version="${{ matrix.version }}"